name: SFDX Test Run on Push

on: [push]


jobs:
    push_to_sf:

        runs-on: ubuntu-latest

        steps:
          # - name: docker image of cumulusci
          #   uses: docker://arcusglobal/cumulusci:1.0
          - name: install homebrew step 1
            run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
          - name: install homebrew step 2
            run: test -d ~/.linuxbrew && eval $(~/.linuxbrew/bin/brew shellenv)
          - name: install homebrew step 3
            run: test -d /home/linuxbrew/.linuxbrew && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
          - name: install homebrew step 4
            run: test -r ~/.bash_profile && echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.bash_profile
          - name: install homebrew step 5
            run: echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.profile
          - name: install cumulusci using homebrew
            run: brew tap SFDO-Tooling/homebrew-sfdo && brew install cumulusci
          - name: checkout current branch
            uses: actions/checkout@master
            with:
               ref: ${{ github.ref }}
          - name: checkout npsp
            uses: actions/checkout@master
            with:
              repository: SalesforceFoundation/NPSP
              path: NPSP
          - name: open NPSP
            run: cd NPSP
          - name: look at NPSP files
            run: ls NPSP
          - name: cci org list
            run: cci org list
          # - uses: sfdx-actions/setup-sfdx@v1
          #   with:
          #     sfdx-auth-url: ${{ secrets.AUTH_SECRET }}
          # - name: push branch to authorized salesforce org
          #   run: sfdx force:source:deploy --sourcepath force-app/main/default --json --loglevel fatal
          # - name: run local tests on salesforce org
          #   run: sfdx force:apex:test:run -l RunLocalTests -w 30