name: SFDX Test Run on Push

on: [push]


jobs:
    push_to_sf:

        runs-on: ubuntu-latest

        steps:
          - name: Checkout Repo
            with:
               ref: ${{ github.ref }}
          - name: output-directory
            run: ls -a
        #         working-directory: ./force-app
          - name: output-directory
            run: cd ~
          - name: output-directory
            run: ls -a
        #       - name: Zip Folder
        #         run: zip -r release.zip .
     
    test:
  
        runs-on: ubuntu-latest

        steps:
          - uses: sfdx-actions/setup-sfdx@v1
            with:
              sfdx-auth-url: ${{ secrets.AUTH_SECRET }}
    #       - name: sfdx-test-run
    #         run: sfdx force:apex:test:run -l RunLocalTests -w 30
          - name: output-directory
            run: ls -a
          - name: output-directory
            run: cd ~
          - name: output-directory
            run: ls -a
    #       - name: Zip Folder
    #         run: zip -r release.zip .
